DECLARE @TOTALREGISTROS INT
DECLARE @CHAVEINICIAL INT
DECLARE @CHAVESELECIONADA INT
DECLARE @QTDE INT

DECLARE @CONTADORINICIAL INT
DECLARE @CONTADORFINAL INT

DECLARE @TABELACHAVE TABLE(CHAVE INT NOT NULL PRIMARY KEY)
DECLARE @VERIFICACHAVE INT

SET @CONTADORINICIAL = 0
SET @CONTADORFINAL = 100

WHILE (@CONTADORINICIAL <> @CONTADORFINAL)
BEGIN
SET @QTDE = 0
SET @VERIFICACHAVE = 0
	WHILE(@QTDE = 0 AND @VERIFICACHAVE = 0)
	BEGIN
		SET @TOTALREGISTROS = (SELECT COUNT(*) FROM Funcionario_Dados_Pessoais_Temp)
		SET @CHAVEINICIAL = (SELECT MIN(ID_Funcionario_Temp) FROM Funcionario_Dados_Pessoais_Temp)
		SET @CHAVESELECIONADA = (SELECT FLOOR(RAND()*(@TOTALREGISTROS-@CHAVEINICIAL)+@CHAVEINICIAL))
		SET @QTDE = (SELECT COUNT(*) FROM Funcionario_Dados_Pessoais_Temp WHERE ID_Funcionario_Temp = @CHAVESELECIONADA)
		SET @VERIFICACHAVE = (SELECT COUNT(*) FROM @TABELACHAVE WHERE CHAVE = @CHAVESELECIONADA)
	END
		INSERT INTO @TABELACHAVE(CHAVE) VALUES (@CHAVESELECIONADA)
		SET @CONTADORINICIAL = @CONTADORINICIAL + 1
END


SELECT * FROM @TABELACHAVE
GO
