MISSÃO PARA O ENCONTRO 09

1) DATABASE ATACADO202204
1.1) ADICIONAR A COLUNA DataAlteracao DATETIME NULL
1.2) ADICIONAR A COLUNA DataExclusao DATETIME NULL
2) ADICIONAR A TABELA CLIENTE.
3) ADICIONAR A TABELA CARRINHO.
4) ADICIONAR A TABELA CARRINHO_ITENS.
5) ADICIONAR A TABELA PEDIDO
