INSERT INTO Cartas (nome_carta, tipo_carta, descricao_carta, regiao_carta) VALUES
	('Fizz', 'Campeão', '1 Mana, 2/1, Elusivo', 'Bilgewater/Bandópolis'),
	('Kennen', 'Campeão', '1 Mana, 2/1, Atk.Rápido', 'Ionia/Bandópolis'),
	('Teemo', 'Campeão', '1 Mana, 2/1, Elusivo', 'Piltover/Bandópolis'),
	('Zoe', 'Campeão', '1 Mana, 1/1, Elusivo', 'Targon'),
	('Ahri', 'Campeão', '2 Manas, 2/2, Atk.Rápido/Elusivo', 'Ionia'),
	('Akshan', 'Campeão', '2 Manas, 2/2, Atk.Rápido', 'Shurima'),
	('Diana', 'Campeão', '2 Manas, 2/2, Atk.Rápido/Desfiador', 'Targon'),
	('Elise', 'Campeão', '2 Manas, 2/3, Assustador/Desafiador', 'Ilha das Sombras'),
	('Lucian', 'Campeão', '2 Mana, 3/2, Atk.Rápido/Atk.Duplo', 'Demacia'),
	('Zilean', 'Campeão', '2 Manas, 1/4', 'Shurima'),
	('Aphelios', 'Campeão', '3 Manas, 3/3, Atk.Rápido', 'Targon'),
	('Azir', 'Campeão', '3 Manas, 1/5', 'Shurima'),
	('Caitlyn', 'Campeão', '3 Manas, 3/3, Atk.Rápido', 'Piltover'),
	('Draven', 'Campeão', '3 Manas, 3/2, Atk.Rápido/Sobrepujar', 'Noxus'),
	('Ezreal', 'Campeão', '3 Manas, 1/3, Elusivo', 'Piltover'),
	('Fiora', 'Campeão', '3 Manas, 3/2, Desafiador', 'Demacia'),
	('Irelia', 'Campeão', '3 Manas, 3/2, Atk.Rápido', 'Ionia'),
	('Kalista', 'Campeão', '3 Manas, 4/3, Assustador', 'Ilha das Sombras'),
	('Katarina', 'Campeão', '3 Manas, 3/2, Atk.Rápido', 'Noxus'),
	('LeBlanc', 'Campeão', '3 Manas, 5/2, Atk.Rápido', 'Noxus'),
	('Lissandra', 'Campeão', '3 Manas, 2/3, Robusto', 'Freljord'),
	('Lulu', 'Campeão', '3 Manas, 3/3', 'Ionia/Bandópolis'),
	('Miss Fortune', 'Campeão', '3 Manas, 3/3, Sobrepujar', 'Bilgewater'),
	('Nami', 'Campeão', '3 Manas, 2/3, Sintonia', 'Bilgewater'),
	('Rek sai', 'Campeão', '3 Manas, 3/6, Sobrepujar', 'Shurima'),
	('Riven', 'Campeão', '3 Manas, 3/4', 'Noxus'),
	('Soraka', 'Campeão', '3 Manas, 1/6', 'Targon'),
	('Tristana', 'Campeão', '3 Manas, 1/3, Atk.Rápido/Impacto', 'Bandópolis'),
	('Yuumi', 'Campeão', '3 Manas, 2/2, Conectar', 'Targon/Bandópolis'),
	('Zed', 'Campeão', '3 Manas, 3/2, Atk.Rápido', 'Ionia'),
	('Ziggs', 'Campeão', '3 Manas, 3/4', 'Shurima/Bandópolis'),
	('Ashe', 'Campeão', '4 Manas, 5/3', 'Freljord'),
	('Braum', 'Campeão', '4 Manas, 0/6, Desafiador/Regeneração', 'Freljord'),
	('Ekko', 'Campeão', '4 Manas, 4/2, Atk.Rápido', 'Piltover'),
	('Gnar', 'Campeão', '4 Manas, 3/3, Atk.Rápido/Sobrepujar', 'Freljord'),
	('Jayce', 'Campeão', '4 Manas, 4/4, Desafiador/Atk.Rápido', 'Piltover');
	
	INSERT INTO Cartas (nome_carta, tipo_carta, descricao_carta, regiao_carta) VALUES
	('Jinx', 'Campeão', '4 Manas, 4/3, Atk.Rápido', 'Piltover'),
	('Kindred', 'Campeão', '4 Manas, 4/3, Atk.Rápido', 'Ilha das Sombras'),
	('Leona', 'Campeão', '4 Manas, 3/5', 'Targon'),
	('Maokai', 'Campeão', '4 Manas, 1/4, Regeneração', 'Ilha das Sombras'),
	('Nocturne', 'Campeão', '4 Manas, 5/3, Assustador', 'Ilha das Sombras'),
	('Pantheon', 'Campeão', '4 Manas, 3/2, Sobrepujar/Barreira/Destinado', 'Targon'),
	('Poppy', 'Campeão', '4 Manas, 2/3, Impacto', 'Bandópolis/Demacia'),
	('Pyker', 'Campeão', '4 Manas, 1/3, Atk.Rápido/Espreitador', 'Bilgewater'),
	('Renekton', 'Campeão', '4 Manas, 4/4, Sobrepujar', 'Shurima'),
	('Rumble', 'Campeão', '4 Manas, 5/4, Atk.Rápido/Impacto/Escudo de Feitiço', 'Bandópolis/Noxus'),
	('Shen', 'Campeão', '4 Manas, 3/5' , 'Ionia'),
	('Shyvana', 'Campeão', '4 Manas, 3/4, Fúria', 'Demacia'),
	('Sivir', 'Campeão', '4 Manas, 5/3, Atk.Rápido/Escudo de Feitiço', 'Shurima'),
	('Tahm Kench', 'Campeão', '4 Manas, 2/6', 'Bilgewater'),
	('Taric', 'Campeão', '4 Manas, 3/5, Robusto', 'Targon'),
	('Twisted Fate', 'Campeão', '4 Manas, 2/2, Atk.Rápido', 'Bilgewater'),
	('Veigar', 'Campeão', '4 Manas, 1/4', 'Bandópolis/Ilha das Sombras'),
	('Viktor', 'Campeão', '4 Manas, 2/4, Aperfeiçoar', 'Piltover'),
	('Xerath', 'Campeão', '4 Manas, 3/4', 'Shurima'),
	('Yasuo', 'Campeão', '4 Manas, 4/4, Atk.Rápido', 'Ionia'),
	('Gangplank', 'Campeão', '5 Manas, 5/4, Sobrepujar', 'Bilgewater'),
	('Garen', 'Campeão', '5 Manas, 5/5, Regeneração', 'Demacia'),
	('Heimerdinger', 'Campeão', '5 Manas, 2/4', 'Piltover/Bandópolis'),
	('Karma', 'Campeão', '5 Manas, 4/3', 'Ionia'),
	('Lee Sin', 'Campeão', '5 Manas, 3/5, Desafiador/Barreira', 'Ionia'),
	('Lux', 'Campeão', '5 Manas, 3/5, Barreira', 'Demacia'),
	('Quinn', 'Campeão', '5 Manas, 3/5, Patrulheiro', 'Demacia'),
	('Senna', 'Campeão', '5 Manas, 4/4, Atk.Rápido', 'Ilha das Sombras'),
	('Swain', 'Campeão', '5 Manas, 3/6, Assustador', 'Noxus'),
	('Taliyah', 'Campeão', '5 Manas, 3/5', 'Shurima'),
	('Thresh', 'Campeão', '5 Manas, 3/6, Desafiador', 'Ilha das Sombras'),
	('Trundle', 'Campeão', '5 Manas, 4/6, Regeneração/Sobrepujar', 'Freljord'),
	('Udyr', 'Campeão', '5 Manas, 4/4', 'Freljord'),
	('Vi', 'Campeão', '5 Manas, 2/4, Desafiador/Robusto', 'Piltover'),
	('Viego', 'Campeão', '5 Manas, 5/4, Assustador', 'Ilha das Sombras'),
	('Vladimir', 'Campeão', '5 Manas, 5/5, Regeneração', 'Noxus'),
	('Anivia', 'Campeão', '6 Manas, 3/5', 'Freljord'),
	('Darius', 'Campeão', '6 Manas, 6/6, Sobrepujar', 'Noxus'),
	('Hecarim', 'Campeão', '6 Manas, 5/6, Sobrepujar', 'Ilha das Sombras'),
	('Jarvan IV', 'Campeão', '6 Manas, 6/4, Barreira', 'Demacia'),
	('Nasus', 'Campeão', '6 Manas, 2/2, Assustador/Escudo de Feitiço', 'Shurima'),
	('Sejuani', 'Campeão', '6 Manas, 5/6, Sobrepujar', 'Freljord'),
	('Galio', 'Campeão', '7 Manas, 0/8, Escudo de Feitiço/Formidável', 'Demacia'),
	('Malphite', 'Campeão', '7 Manas, 6/10, Robusto', 'Targon'),
	('Nautilus', 'Campeão', '7 Manas, 0/12, Robusto/Assustador', 'Bilgewater'),
	('Sion', 'Campeão', '7 Manas, 1/6, Sobrepujar', 'Noxus'),
	('Tryndamere', 'Campeão', '8 Manas, 8/4, Assustador/Robusto/Sobrepujar', 'Freljord'),
	('Aurelion Sol', 'Campeão', '10 Manas, 10/10, Escudo de Feitiço/Fúria', 'Targon');

	
	
	
