INSERT INTO Cartas (nome_carta, tipo_carta, descricao_carta, regiao_carta) VALUES
	('Fizz', 'Campeão', '1 Mana, 2/1, Elusivo', 'Bilgewater/Bandópolis'),
	('Kennen', 'Campeão', '1 Mana, 2/1, Atk.Rápido', 'Ionia/Bandópolis'),
	('Teemo', 'Campeão', '1 Mana, 2/1, Elusivo', 'Piltover/Bandópolis'),
	('Zoe', 'Campeão', '1 Mana, 1/1, Elusivo', 'Targon'),
	('Ahri', 'Campeão', '2 Manas, 2/2, Atk.Rápido/Elusivo', 'Ionia'),
	('Akshan', 'Campeão', '2 Manas, 2/2, Atk.Rápido', 'Shurima'),
	('Diana', 'Campeão', '2 Manas, 2/2, Atk.Rápido/Desfiador', 'Targon'),
	('Elise', 'Campeão', '2 Manas, 2/3, Assustador/Desafiador', 'Ilha das Sombras'),
	('Lucian', 'Campeão', '2 Mana, 3/2, Atk.Rápido/Atk.Duplo', 'Demacia'),
	('Zilean', 'Campeão', '2 Manas, 1/4', 'Shurima'),
	('Aphelios', 'Campeão', '3 Manas, 3/3, Atk.Rápido', 'Targon'),
	('Azir', 'Campeão', '3 Manas, 1/5', 'Shurima'),
	('Caitlyn', 'Campeão', '3 Manas, 3/3, Atk.Rápido', 'Piltover'),
	('Draven', 'Campeão', '3 Manas, 3/2, Atk.Rápido/Sobrepujar', 'Noxus'),
	('Ezreal', 'Campeão', '3 Manas, 1/3, Elusivo', 'Piltover'),
	('Fiora', 'Campeão', '3 Manas, 3/2, Desafiador', 'Demacia'),
	('Irelia', 'Campeão', '3 Manas, 3/2, Atk.Rápido', 'Ionia'),
	('Kalista', 'Campeão', '3 Manas, 4/3, Assustador', 'Ilha das Sombras'),
	('Katarina', 'Campeão', '3 Manas, 3/2, Atk.Rápido', 'Noxus'),
	('LeBlanc', 'Campeão', '3 Manas, 5/2, Atk.Rápido', 'Noxus'),
	('Lissandra', 'Campeão', '3 Manas, 2/3, Robusto', 'Freljord'),
	('Lulu', 'Campeão', '3 Manas, 3/3', 'Ionia/Bandópolis'),
	('Miss Fortune', 'Campeão', '3 Manas, 3/3, Sobrepujar', 'Bilgewater'),
	('Nami', 'Campeão', '3 Manas, 2/3, Sintonia', 'Bilgewater'),
	('Rek sai', 'Campeão', '3 Manas, 3/6, Sobrepujar', 'Shurima'),
	('Riven', 'Campeão', '3 Manas, 3/4', 'Noxus'),
	('Soraka', 'Campeão', '3 Manas, 1/6', 'Targon'),
	('Tristana', 'Campeão', '3 Manas, 1/3, Atk.Rápido/Impacto', 'Bandópolis'),
	('Yuumi', 'Campeão', '3 Manas, 2/2, Conectar', 'Targon/Bandópolis'),
	('Zed', 'Campeão', '3 Manas, 3/2, Atk.Rápido', 'Ionia'),
	('Ziggs', 'Campeão', '3 Manas, 3/4', 'Shurima/Bandópolis'),
	('Ashe', 'Campeão', '4 Manas, 5/3', 'Freljord'),
	('Braum', 'Campeão', '4 Manas, 0/6, Desafiador/Regeneração', 'Freljord'),
	('Ekko', 'Campeão', '4 Manas, 4/2, Atk.Rápido', 'Piltover'),
	('Gnar', 'Campeão', '4 Manas, 3/3, Atk.Rápido/Sobrepujar', 'Freljord'),
	('Jayce', 'Campeão', '4 Manas, 4/4, Desafiador/Atk.Rápido', 'Piltover');
	
	
	
